#!/usr/bin/perl

use Modern::Perl '2010';
use strict;

my $against;
my $out = qx{git rev-parse --verify HEAD};

if ( $out ne '' ) {
    $against = 'HEAD';
}
else {
    $against = '4b825dc642cb6eb9a060e54bf8d69288fbee4904';
}

my $cmd =
"date >> ./pre-commit.log; git diff --cached --name-only $against >> ./pre-commit.log";

system($cmd);

exit(0);
